solver_cfg:
  solver: 'cplex'
  tee: True  # output solver
 
input_files:
  data: './case1/Input_data.xlsx'

output_files:
  folder: './Ouput_Model1'
  filename: 'Output.xlsx'
  results_folder: 'Results'
  
  